### DISCUSSION TITLE
支持自定义中英文字体

### DISCUSSION THREAD

**Discussion by HaixinRen** [CherryHQ/cherry-studio#2147] [Ideas] [answered]
如题，希望可以自定义UI与对话界面的中英文字体。

**Comment by ousugo** [comment, marked as answer]
通过自定义 CSS 功能可以实现

**Reply by HaixinRen** [reply]
好的十分感谢，但是我在自定义css中试图将字体切换为微软雅黑时，输入了如下代码“@font-face {
  font-family: 'Microsoft YaHei';
  src: url('MSYH.ttc') format('truetype');
  font-weight: normal;
  font-style: normal;
}”却没有反应，这是为什么呢？

**Reply by LBEILC** [reply]
> 好的十分感谢，但是我在自定义css中试图将字体切换为微软雅黑时，输入了如下代码“@font-face { font-family: 'Microsoft YaHei'; src: url('MSYH.ttc') format('truetype'); font-weight: normal; font-style: normal; }”却没有反应，这是为什么呢？

https://linux.do/t/topic/325119/13 这个自定义主题下有一些字体修改的相关设置，直接修改字体的话是
`* {
  font-family: "字体名字" !important;
}`

**Reply by HaixinRen** [reply]
已经成功了，非常感谢！

**Comment by otakutyrant** [comment]
I tried to change chat font size and this may works:

```
.MessageContentContainer-gQbqsP {
  font-size: 20px !important; /* Or your desired size */
}
```

**Reply by gongjue** [reply]
Cherry Studio is built on Electron, which allows you to open Chrome DevTools to inspect elements. You can typically open DevTools using:
* Windows/Linux: `Ctrl+Shift+I`
* Mac: `Cmd+Option+I`

Then you can find the element id and class to customize. I end up with this setting:

```css
.message-content-container,
.message-content-container h1,
.message-content-container h2,
.message-content-container h3,
.message-content-container h4,
.message-content-container h5,
.message-content-container h6 {
  font-family: "Charter", "Songti SC" !important;
}

#content-container,
#SettingContent-bYawOk,
.Container-kFeIMJ,
.ServerNameText-jHmATg,
.NameSpan-jCfojk,
.ProviderItemName-cTlbYU,
.Description-BbZVu,
.name,
.message-tokens {
  font-family: -apple-system !important;
}
```
To make the chat font as serif and the UI as sans serif. Also the default sans serif font is ubuntu and I change to `-apple-system` to keep consistent with Mac style.
