### ISSUE TITLE
需求：自定义界面字体

### ISSUE THREAD

**Issue by uu-space** [CherryHQ/cherry-studio#158]
你好，请问未来是否会考虑新增自定义字体的功能呢，windows的字体真是一言难尽🙈

**Comment by kangfenmao** [comment]
可以

**Comment by pengshp** [comment]
还有增加字体大小的选择范围，最大只能到18, 在高分辨率显示器下感觉还是有点小，建议到最大到24

**Comment by kangfenmao** [comment]
这个下个版本上。

不过高分屏，建议开启系统级别缩放，不然很多软件都会显得很小

**Comment by kangfenmao** [comment]
增加了字体大小选择范围到 22

**Comment by NpTIme** [comment]
> 增加了字体大小选择范围到 22

请问这个功能具体什么时候上线

**Comment by marvyn** [comment]
建议代码部分的字体可以自定义

**Comment by pengshp** [comment]
可以使用`显示设置`里的`自定义CSS`功能修改字体
例如修改代码字体
```scss
body[theme-mode="dark"] {
    code {
        font-family: "CaskaydiaCove Nerd Font Mono",苹方-简,monospace;
    }
}
```
根据自己的需要修改你的字体，设置一个中文字体作为fallback字体，不然会使用难看的宋体字。
上面是Dark主题生效，同样可以再复制一份代码改为Light主题
