### ISSUE TITLE
[Bug]: 使用自定义css修改全局字体样式后覆盖代码块字体

### ISSUE THREAD

**Issue by LBEILC** [CherryHQ/cherry-studio#2244]
### Issue Checklist

- [x] I understand that issues are for feedback and problem solving, not for complaining in the comment section, and will provide as much information as possible to help solve the problem.
- [x] I've looked at pinned issues and searched for existing [Open Issues](https://github.com/CherryHQ/cherry-studio/issues), [Closed Issues](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed), and [Discussions](https://github.com/CherryHQ/cherry-studio/discussions), no similar issue or discussion was found.
- [x] I've filled in short, clear headings so that developers can quickly identify a rough idea of what to expect when flipping through the list of issues. And not "a suggestion", "stuck", etc.

### Platform

Windows

### Version

v1.0.0

### Bug Description

使用如下css代码自定义样式：
``` css
:root {
  /* 原子化设计令牌 */
  --duration-quick: 0.15s;
  --easing-emphasized: cubic-bezier(0.2, 0, 0, 1);
  --easing-decelerate: cubic-bezier(0, 0, 0.2, 1);
  --radius-dynamic: clamp(8px, (100% - 40px) * 0.015, 16px);
  --radius-large: clamp(12px, (100% - 60px) * 0.02, 24px);
  
  /* OKLCH色彩空间 */
  --color-brand-primary: oklch(62.8% 0.25 29.2);
  --color-brand-hover: color-mix(in oklch, var(--color-brand-primary) 90%, black);
  
  /* 动态主题参数 */
  --theme-lightness: 1; /* 1=light, -1=dark */
  --shadow-intensity: 0.04;
}

/* 基础架构 */
* {
  font-family: "MiSans Regular", system-ui;
  line-height: 1.7;
  letter-spacing: 0.018em;
}

/* 使用通用等宽字体族名 + 具体字体名称 */
.shiki.one-light code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.shiki.material-theme-darker code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.message-content-container {
  /* 物理渲染层 */
  transform: translateZ(0);
  will-change: transform, box-shadow;
  contain: layout paint style;

  /* 动态样式 */
  background: hsl(
    calc(240 * var(--theme-lightness)),
    calc(5% * abs(var(--theme-lightness))),
    calc(98% - 76% * var(--theme-lightness))
  ) !important;
  
  /* 增量过渡 */
  transition: 
    transform var(--duration-quick) var(--easing-emphasized),
    box-shadow 0.4s var(--easing-decelerate),
    background-color 1s linear,
    border-radius 0.3s var(--easing-decelerate);

  /* 逻辑属性 */
  margin-block: 8px;
  padding-inline: 12px;
  padding-block: 10px;

  /* 悬停状态 */
  &:hover {
    border-radius: var(--radius-large);
  }
}


/* 输入栏优化 */
#inputbar {
  background: color-mix(
    in oklab,
    var(--chat-background-white),
    transparent 4%
  ) !important;
  backdrop-filter: blur(8px);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-large);
  margin: -15px 20px 15px 20px;
}

/* 暗色主题 */
body[theme-mode='dark'] {
  --theme-lightness: -1;
  --shadow-intensity: 0.4;
  
  .message-content-container {
    background: hsl(
      calc(200 + 40 * var(--theme-lightness)),
      calc(8% * abs(var(--theme-lightness))),
      calc(16% + 6% * var(--theme-lightness))
    ) !important;
    
    border-color: color-mix(
      in oklch, 
      var(--color-brand-primary), 
      transparent 88%
    );
  }
  
  #inputbar {
    background: color-mix(
      in oklab,
      var(--chat-background-white),
      black 6%
    ) !important;
  }
}

/* 触摸设备适配 */
@media (pointer: coarse) {
  .message-content-container {
    min-block-size: 44px;
    --shadow-intensity: calc(var(--shadow-intensity) * 2);
    
    transition: 
      transform var(--duration-quick) var(--easing-emphasized),
      box-shadow 0.3s linear,
      border-radius 0.3s var(--easing-decelerate);
  }
}

/* 高对比度模式 */
@media (prefers-contrast: more) {
  .message-content-container {
    border-width: 2px;
    
    &::after {
      content: "";
      display: block;
      border: 1px solid CanvasText;
      border-radius: inherit;
    }
  }
}
```

按照css选择器优先级来说
``` css
* {
  font-family: "MiSans Regular", system-ui;
  line-height: 1.7;
  letter-spacing: 0.018em;
}
```
无法覆盖
``` css
/* 使用通用等宽字体族名 + 具体字体名称 */
.shiki.one-light code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.shiki.material-theme-darker code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}
```
但从结果来看，代码块样式被覆盖，通过控制台来看也没有被覆盖，但在控制台取消全局字体样式后能成功应用代码快样式

### Steps To Reproduce

使用如下css代码自定义样式：
``` css
:root {
  /* 原子化设计令牌 */
  --duration-quick: 0.15s;
  --easing-emphasized: cubic-bezier(0.2, 0, 0, 1);
  --easing-decelerate: cubic-bezier(0, 0, 0.2, 1);
  --radius-dynamic: clamp(8px, (100% - 40px) * 0.015, 16px);
  --radius-large: clamp(12px, (100% - 60px) * 0.02, 24px);
  
  /* OKLCH色彩空间 */
  --color-brand-primary: oklch(62.8% 0.25 29.2);
  --color-brand-hover: color-mix(in oklch, var(--color-brand-primary) 90%, black);
  
  /* 动态主题参数 */
  --theme-lightness: 1; /* 1=light, -1=dark */
  --shadow-intensity: 0.04;
}

/* 基础架构 */
* {
  font-family: "MiSans Regular", system-ui;
  line-height: 1.7;
  letter-spacing: 0.018em;
}

/* 使用通用等宽字体族名 + 具体字体名称 */
.shiki.one-light code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.shiki.material-theme-darker code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.message-content-container {
  /* 物理渲染层 */
  transform: translateZ(0);
  will-change: transform, box-shadow;
  contain: layout paint style;

  /* 动态样式 */
  background: hsl(
    calc(240 * var(--theme-lightness)),
    calc(5% * abs(var(--theme-lightness))),
    calc(98% - 76% * var(--theme-lightness))
  ) !important;
  
  /* 增量过渡 */
  transition: 
    transform var(--duration-quick) var(--easing-emphasized),
    box-shadow 0.4s var(--easing-decelerate),
    background-color 1s linear,
    border-radius 0.3s var(--easing-decelerate);

  /* 逻辑属性 */
  margin-block: 8px;
  padding-inline: 12px;
  padding-block: 10px;

  /* 悬停状态 */
  &:hover {
    border-radius: var(--radius-large);
  }
}


/* 输入栏优化 */
#inputbar {
  background: color-mix(
    in oklab,
    var(--chat-background-white),
    transparent 4%
  ) !important;
  backdrop-filter: blur(8px);
  border: 1px solid var(--color-border);
  border-radius: var(--radius-large);
  margin: -15px 20px 15px 20px;
}

/* 暗色主题 */
body[theme-mode='dark'] {
  --theme-lightness: -1;
  --shadow-intensity: 0.4;
  
  .message-content-container {
    background: hsl(
      calc(200 + 40 * var(--theme-lightness)),
      calc(8% * abs(var(--theme-lightness))),
      calc(16% + 6% * var(--theme-lightness))
    ) !important;
    
    border-color: color-mix(
      in oklch, 
      var(--color-brand-primary), 
      transparent 88%
    );
  }
  
  #inputbar {
    background: color-mix(
      in oklab,
      var(--chat-background-white),
      black 6%
    ) !important;
  }
}

/* 触摸设备适配 */
@media (pointer: coarse) {
  .message-content-container {
    min-block-size: 44px;
    --shadow-intensity: calc(var(--shadow-intensity) * 2);
    
    transition: 
      transform var(--duration-quick) var(--easing-emphasized),
      box-shadow 0.3s linear,
      border-radius 0.3s var(--easing-decelerate);
  }
}

/* 高对比度模式 */
@media (prefers-contrast: more) {
  .message-content-container {
    border-width: 2px;
    
    &::after {
      content: "";
      display: block;
      border: 1px solid CanvasText;
      border-radius: inherit;
    }
  }
}
```

https://github.com/user-attachments/assets/e945e21c-d98f-42cb-b557-b74df0be5ca0

### Expected Behavior

代码块样式通过
``` css
/* 使用通用等宽字体族名 + 具体字体名称 */
.shiki.one-light code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}

.shiki.material-theme-darker code {
  font-family: 
"Cascadia Code", "Fira Code", "Consolas", monospace, "MiSans Regular" !important;
}
```
成功修改

### Relevant Log Output

```shell

```

**Comment by DeJeune** [comment]
* 选择器选择了所有样式，但是你只为code元素本身设置了等宽字体，虽然code 的子元素span会继承等宽字体，但是没有继承!important修饰符。这时候*选择器优先级高于span元素继承的等宽字体，所以等宽字体在span元素上不生效。
所以是自定义css代码的问题

**Comment by LBEILC** [comment]
> *选择器选择了所有样式，但是你只为code元素本身设置了等宽字体，虽然code 的子元素span会继承等宽字体，但是没有继承!important修饰符。这时候*选择器优先级高于span元素继承的等宽字体，所以等宽字体在span元素上不生效。 所以是自定义css代码的问题

感谢解答，修改为
``` css
/* 使用通用等宽字体族名 + 具体字体名称 */
.shiki.one-light code span {
  font-family: 
"Cascadia Code", "苹方-简" !important;
}

.shiki.material-theme-darker code span {
  font-family: 
"Cascadia Code", "苹方-简" !important;
}
```
后正常了
