### ISSUE TITLE
[错误]: searxng 添加失败，一直都是验证失败。

### ISSUE THREAD

**Issue by maryjeck** [CherryHQ/cherry-studio#3476]
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了置顶 Issue 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.1.5

### 错误描述

searxng一直检测失败

### 重现步骤

docker 部署，网页能正常搜索

### 预期行为

能够正常的使用

### 相关日志输出

```shell

```

**Comment by hshh** [comment]
那是因为 searxng 的 limiter 导致的

**Comment by Githubsanae** [comment]
同样的问题，内网部署的searxng不能通过测试

**Comment by hjy2000** [comment]
同，验证失败

**Comment by tommyzhang100504** [comment]
> 在配置文件中将返回格式 加上 json
> 
> ![Image](https://github.com/user-attachments/assets/bf82fcec-7bfd-4f8a-a1d9-2de4de0796af)

感谢，修改这个地方就能用了

**Comment by AIexon** [comment]
### settings.yml
如果没有加上json的话 http://<yourinstance>:8080/search?q=test&format=json 会 return 403， 我在加入MCP-SEARXNG 的时候也是遇到这情况。
```
alpine-docker:~/searxng-docker# cat searxng/
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "fe85e1ded989e689de94a892f3f1220125ee692b4ae"
  limiter: false  # can be disabled for a private instance
  image_proxy: true
ui:
  static_use_hash: true
redis:
  url: redis://redis:6379/0
search:
  formats:
    - html
    - json
```

### docker-compose.yaml
我用的访问地址是 `http://localhost:8100`  , 可以更据喜好自己更改它的 port （8100）。
如果localhost不行可以尝试换成 `http://host.docker.internal:8100`
```
version: "3.7"
services:
  redis:
    container_name: redis
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - valkey-data2:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      - searxng
    ports:
      - "8100:8080"  # Changed to expose port 8100 externally
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=http://localhost:8100/   
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    # Temporarily comment out cap_drop for first run
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
networks:
  searxng:
volumes:
  valkey-data2:
```

**Comment by zhychen1173** [comment]
我也遇到这个问题。内网部署的searxng，同一个服务，lobechat就可以正常联网搜索，cherry-studio一直验证失败。

![Image](https://github.com/user-attachments/assets/acdd149f-14c3-4dd8-a08d-cc0bef9443b6)

![Image](https://github.com/user-attachments/assets/d723be85-ae94-41d7-bb2d-89c039054a19)

![Image](https://github.com/user-attachments/assets/385b4b91-db24-46fa-be46-3725853058eb)

**Comment by Mano-Liaoyan** [comment]
> ### settings.yml
> 
> 如果没有加上json的话 http://yourinstance:8080/search?q=test&format=json 会 return 403， 我在加入MCP-SEARXNG 的时候也是遇到这情况。
> 
> ```
> alpine-docker:~/searxng-docker# cat searxng/
> use_default_settings: true
> server:
>   # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
>   secret_key: "fe85e1ded989e689de94a892f3f1220125ee692b4ae"
>   limiter: false  # can be disabled for a private instance
>   image_proxy: true
> ui:
>   static_use_hash: true
> redis:
>   url: redis://redis:6379/0
> search:
>   formats:
>     - html
>     - json
> ```
> 
> ### docker-compose.yaml
> 
> 我用的访问地址是 `http://localhost:8100` , 可以更据喜好自己更改它的 port （8100）。 如果localhost不行可以尝试换成 `http://host.docker.internal:8100`
> 
> ```
> version: "3.7"
> services:
>   redis:
>     container_name: redis
>     image: docker.io/valkey/valkey:8-alpine
>     command: valkey-server --save 30 1 --loglevel warning
>     restart: unless-stopped
>     networks:
>       - searxng
>     volumes:
>       - valkey-data2:/data
>     cap_drop:
>       - ALL
>     cap_add:
>       - SETGID
>       - SETUID
>       - DAC_OVERRIDE
>     logging:
>       driver: "json-file"
>       options:
>         max-size: "1m"
>         max-file: "1"
>   searxng:
>     container_name: searxng
>     image: docker.io/searxng/searxng:latest
>     restart: unless-stopped
>     networks:
>       - searxng
>     ports:
>       - "8100:8080"  # Changed to expose port 8100 externally
>     volumes:
>       - ./searxng:/etc/searxng:rw
>     environment:
>       - SEARXNG_BASE_URL=http://localhost:8100/   
>       - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
>       - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
>     # Temporarily comment out cap_drop for first run
>     cap_drop:
>       - ALL
>     cap_add:
>       - CHOWN
>       - SETGID
>       - SETUID
>     logging:
>       driver: "json-file"
>       options:
>         max-size: "1m"
>         max-file: "1"
> networks:
>   searxng:
> volumes:
>   valkey-data2:
> ```
> 
> ![Image](https://github.com/user-attachments/assets/f6faff9c-c0df-4f29-85f8-f5a163e042d7) docker 部署在 ip 10.10.10.111 的例子。

请问公网部署需要额外的操作吗？我照着试了下还是不行。浏览器是正常的

**Comment by Mano-Liaoyan** [comment]
> > ### settings.yml
> > 如果没有加上json的话 http://yourinstance:8080/search?q=test&format=json 会 return 403， 我在加入MCP-SEARXNG 的时候也是遇到这情况。
> > ```
> > alpine-docker:~/searxng-docker# cat searxng/
> > use_default_settings: true
> > server:
> >   # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
> >   secret_key: "fe85e1ded989e689de94a892f3f1220125ee692b4ae"
> >   limiter: false  # can be disabled for a private instance
> >   image_proxy: true
> > ui:
> >   static_use_hash: true
> > redis:
> >   url: redis://redis:6379/0
> > search:
> >   formats:
> >     - html
> >     - json
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### docker-compose.yaml
> > 我用的访问地址是 `http://localhost:8100` , 可以更据喜好自己更改它的 port （8100）。 如果localhost不行可以尝试换成 `http://host.docker.internal:8100`
> > ```
> > version: "3.7"
> > services:
> >   redis:
> >     container_name: redis
> >     image: docker.io/valkey/valkey:8-alpine
> >     command: valkey-server --save 30 1 --loglevel warning
> >     restart: unless-stopped
> >     networks:
> >       - searxng
> >     volumes:
> >       - valkey-data2:/data
> >     cap_drop:
> >       - ALL
> >     cap_add:
> >       - SETGID
> >       - SETUID
> >       - DAC_OVERRIDE
> >     logging:
> >       driver: "json-file"
> >       options:
> >         max-size: "1m"
> >         max-file: "1"
> >   searxng:
> >     container_name: searxng
> >     image: docker.io/searxng/searxng:latest
> >     restart: unless-stopped
> >     networks:
> >       - searxng
> >     ports:
> >       - "8100:8080"  # Changed to expose port 8100 externally
> >     volumes:
> >       - ./searxng:/etc/searxng:rw
> >     environment:
> >       - SEARXNG_BASE_URL=http://localhost:8100/   
> >       - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
> >       - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
> >     # Temporarily comment out cap_drop for first run
> >     cap_drop:
> >       - ALL
> >     cap_add:
> >       - CHOWN
> >       - SETGID
> >       - SETUID
> >     logging:
> >       driver: "json-file"
> >       options:
> >         max-size: "1m"
> >         max-file: "1"
> > networks:
> >   searxng:
> > volumes:
> >   valkey-data2:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Image](https://github.com/user-attachments/assets/f6faff9c-c0df-4f29-85f8-f5a163e042d7) docker 部署在 ip 10.10.10.111 的例子。
> 
> 请问公网部署需要额外的操作吗？我照着试了下还是不行。浏览器是正常的
附上设置

![Image](https://github.com/user-attachments/assets/a25deb00-d4f5-4e6c-a010-fce6743992af)

**Comment by AIexon** [comment]
你可以先用curl尝试， 看有没有return 403
```
curl "http://10.10.10.111:8100/search?q=artificial+intelligence&format=json" 
```

公网也是一样的, 确保reverse proxy 指向searxng-docker的 IP 和 端口 http://10.10.10.111 & 8100 （default 是8080） ：
```
curl "https://your-instance.duckdns.org/search?q=artificial+intelligence&format=json" 
```

**Comment by Mano-Liaoyan** [comment]
感谢各位，使用 curl 后发现返回的是 429 Too Many Requests Error. 经过查询发现是 searxng 的 limiter 配置文件阻碍了 API访问。将其在设置中设为 false 以后正常，如下图所示

<img width="994" alt="Image" src="https://github.com/user-attachments/assets/b7bab0ca-3fa3-4a80-a15f-06e50096e9d2" />

**Comment by vasoul** [comment]
我用浏览器可以正常访问
配置里已添加json输出，在浏览器地址中拼接format=json 可以返回json结果
curl返回也是200
limiter是false的
域名配置试过加search和不加都不行

**Comment by wk544863858** [comment]
通过查看原代码和日志，我确定验证不通过的原因是searxng未配置正确的引擎。Cherry Studio会默认选取categories同时包含web general的引擎进行搜索，默认情况下会选中google等引擎，由于大陆无法直接链接google导致失败。增加以下配置使得searxng强制使用baidu引擎，即可解决问题。
```
use_default_settings:
  engines:
    keep_only:
      - baidu
engines:
  - name: baidu
    engine: baidu 
    categories: 
      - web
      - general
    disabled: false
```

By checking the original code and logs, I determined that the reason for the validation failure is that searxng is not configured with the correct engine. Cherry Studio will default to selecting engines that include both categories and web general for search, and will default to selecting engines like Google. However, since the mainland cannot directly link to Google, it fails. Adding the following configuration to force searxng to use the Baidu engine can solve the problem.
