### ISSUE TITLE
[错误]: Cherry Studio 无法正常添加 SearXNG API 服务

### ISSUE THREAD

**Issue by IAMJOYBO** [CherryHQ/cherry-studio#3794]
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了置顶 Issue 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.1.8

### 错误描述

![Image](https://github.com/user-attachments/assets/b373b7de-7667-4cf9-a46e-b8a755914947)

### 重现步骤

1、使用 Docker Compose 部署

2、修改的配置如下：

![Image](https://github.com/user-attachments/assets/22d0833b-1902-45eb-9da9-e34fb4920660)

![Image](https://github.com/user-attachments/assets/c5ed2498-700f-49fc-9d37-13709cba3eba)

3、目录结构

![Image](https://github.com/user-attachments/assets/ae6288d3-eeef-435e-ae47-43f8cb56f783)

4、docker-compose.yaml 文件内容

``` yaml

version: "3.7"

services:
  caddy:
    container_name: caddy-searxng
    image: docker.io/library/caddy:2-alpine
    networks:
      - nas
    restart: always
    privileged: true
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy-data:/data:rw
      - ./caddy-config:/config:rw
    environment:
      - SEARXNG_HOSTNAME=${SEARXNG_HOSTNAME:-http://localhost}
      - SEARXNG_TLS=${LETSENCRYPT_EMAIL:-internal}
    cap_add:
      - NET_BIND_SERVICE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  redis:
    container_name: redis-searxng
    image: docker.io/valkey/valkey:8-alpine
    command: valkey-server --save 30 1 --loglevel warning
    restart: always
    privileged: true
    networks:
      - nas
    volumes:
      - ./valkey-data2:/data
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: always
    privileged: true
    networks:
      - nas
    ports:
      - "8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  nas:
    external: true

```

### 预期行为

成功对接

### 相关日志输出

```shell

```
