### ISSUE TITLE
[错误]: MCP服务器找不到自定义安装的bun和uv

### ISSUE THREAD

**Issue by morning-start** [CherryHQ/cherry-studio#4018]
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了置顶 Issue 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的问题。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。

### 平台

Windows

### 版本

v1.1.10

### 错误描述

已经安装bun和uv，但是MCP服务器无法检测到

### 重现步骤

我的环境变量如下：

```yaml
bun:
  BUN_INSTALL: D:/Language/Nodejs/bun
  
uv:
  UV_HOME: D:/Language/python/uv
  UV_CACHE_DIR: D:/Language/python/uv/cache
  UV_CONFIG_FILE: D:/Language/python/uv/uv.toml
```

powershell 可以正常使用uv和bun命令

### 预期行为

能够识别到环境变量中的配置

### 相关日志输出

```shell

```
