### ISSUE TITLE
[功能]: 请提供聊天窗口不隐藏滚动条的选项

### ISSUE THREAD

**Issue by szmcdull** [CherryHQ/cherry-studio#4775]
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了置顶 Issue 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的建议。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 最新的 Cherry Studio 版本没有实现我所提出的功能。

### 平台

Windows

### 版本

1.2.2

### 您的功能建议是否与某个问题/issue相关?

AI应该是用来提升效率的，但是隐藏滚动条就相反，麻烦考虑一下，隐藏的滚动条让人抓狂

### 请描述您希望实现的解决方案

提供不隐藏滚动条的选项

**Comment by webwww123** [comment]
还有一个就是滚动条太小，且全屏下不贴边，找老半天

**Comment by africa1207** [comment]
@szmcdull  完成，https://github.com/CherryHQ/cherry-studio/pull/4781

**Comment by teojs** [comment]
建议自行通过自定义css实现吧，把下面这段代码贴到 设置->显示设置->自定义CSS 那里就行了

```css
#messages::-webkit-scrollbar-thumb {
  background: var(--color-scrollbar-thumb) !important;
}
#messages::-webkit-scrollbar-thumb:hover {
 background: var(--color-scrollbar-thumb-hover) !important;
}
```
