### ISSUE TITLE
[功能]: 自定义主题色覆盖范围

### ISSUE THREAD

**Issue by Lucas04-nhr** [CherryHQ/cherry-studio#6685]
### 提交前检查

- [x] 我理解 Issue 是用于反馈和解决问题的，而非吐槽评论区，将尽可能提供更多信息帮助问题解决。
- [x] 我已经查看了置顶 Issue 并搜索了现有的 [开放Issue](https://github.com/CherryHQ/cherry-studio/issues)和[已关闭Issue](https://github.com/CherryHQ/cherry-studio/issues?q=is%3Aissue%20state%3Aclosed%20)，没有找到类似的建议。
- [x] 我填写了简短且清晰明确的标题，以便开发者在翻阅 Issue 列表时能快速确定大致问题。而不是“一个建议”、“卡住了”等。
- [x] 最新的 Cherry Studio 版本没有实现我所提出的功能。

### 平台

macOS

### 版本

v.1.4.0-rc.3

### 您的功能建议是否与某个问题/issue相关?

在更新到最新的Pre-release版本后发现增加了一个“主题颜色”的设置项，可以自定义绝大部分的颜色主题，但是似乎对话界面的气泡并不会根据主题色进行变动。

### 请描述您希望实现的解决方案

将全局CSS变量中的`--chat-background-user`设置为用户自定义的主题色

### 请描述您考虑过的其他方案

目前仅可能通过自定义CSS的方式暂时进行更改

```css
:root {
  --chat-background-user-light: #5698C3;
  --chat-background-user-dark: #2486B9;
  --button-hover-light: #2983BB;
  --button-hover-dark: #2775B6;
}

[theme-mode=light] .bubble .message-user .message-action-button:hover {
  background-color: var(--button-hover-light) !important;
}

[theme-mode=dark] .bubble .message-user .message-action-button:hover {
  background-color: var(--button-hover-dark) !important;
}

[theme-mode=light] .message-content-container-user {
  background-color: var(--chat-background-user-light) !important;
}

[theme-mode=dark] .message-content-container-user {
  background-color: var(--chat-background-user-dark) !important;
}

```

### 其他补充信息

注意到白天/黑暗模式中的`--chat-background-user`变量会被设置成不同的值，如果可以的话希望给每个 Preset 都做出类似的适配(通过改变对应HSV的明度)，同时给用户自定义的选项
